# MyBatis 映射配置
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.demo.backend.entity
  configuration:
    map-underscore-to-camel-case: true

# 应用服务 WEB 访问端口
server:
  port: 8080

# 数据库配置
spring:
  ai:
    openai:
      base-url: https://api.mixrai.com
      api-key: sk-7wqzLhzPhLXsil6D8578011dA0694bE596Fc397c798880E4
  datasource:
    url: jdbc:mysql://localhost:3306/children_storybook?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 200211
    driver-class-name: com.mysql.cj.jdbc.Driver
